services:
  - type: web
    name: kcsc-gpt-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python lightweight_gpts_api_server.py
    branch: main
    autoDeploy: true
    healthCheckPath: /health
