services:
  - type: web
    name: kcsc-gpt-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python render_ready_api_server.py
    branch: main
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: API_KEY
        value: kcsc-gpt-secure-key-2025
      - key: LOG_LEVEL
        value: INFO
